// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJX9ieGxYwXq1FlzSD9U5TojZHNYYcP2s',
    appId: '1:40484261476:web:d937d9198703a36a905971',
    messagingSenderId: '40484261476',
    projectId: 'kade-application01',
    authDomain: 'kade-application01.firebaseapp.com',
    storageBucket: 'kade-application01.firebasestorage.app',
    measurementId: 'G-8J3Q3NHHCH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPpJK_4ci9ijVN00N73r1PS5iAdlhS32Q',
    appId: '1:40484261476:android:932d7942538c44aa905971',
    messagingSenderId: '40484261476',
    projectId: 'kade-application01',
    storageBucket: 'kade-application01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwEECUQmcPGOB5LijnbwAs0pnL7IfF8Os',
    appId: '1:40484261476:ios:e4eefcb176fa6312905971',
    messagingSenderId: '40484261476',
    projectId: 'kade-application01',
    storageBucket: 'kade-application01.firebasestorage.app',
    iosBundleId: 'com.example.kadeApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwEECUQmcPGOB5LijnbwAs0pnL7IfF8Os',
    appId: '1:40484261476:ios:e4eefcb176fa6312905971',
    messagingSenderId: '40484261476',
    projectId: 'kade-application01',
    storageBucket: 'kade-application01.firebasestorage.app',
    iosBundleId: 'com.example.kadeApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJX9ieGxYwXq1FlzSD9U5TojZHNYYcP2s',
    appId: '1:40484261476:web:0edee9897d06742a905971',
    messagingSenderId: '40484261476',
    projectId: 'kade-application01',
    authDomain: 'kade-application01.firebaseapp.com',
    storageBucket: 'kade-application01.firebasestorage.app',
    measurementId: 'G-JXBCSNY5VQ',
  );
}
